### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by OmShrivastava19** [OmShrivastava19/omshrivastava19.github.io#2]

**Comment by JyotiJauhari** [comment]
Please assign me this issue, I will fix the broken links.

**Comment by JyotiJauhari** [comment]
You can assign this to anyone else @OmShrivastava19 . I am not able to work on it.

**Comment by OmShrivastava19** [comment]
Done, now you can start working.

**Comment by harikanani** [comment]
Which links are broke? Can you please tell me I can try to working on it @JyotiJauhari
